global using Grpc.Net.Client;
global using IdentityModel.Client;
global using Microsoft.Extensions.Options;
global using ShoppingCartGrpc;
global using ShoppingCartWorkerService;
global using ShoppingCartWorkerService.Options;
global using ProductGrpc;
global using Grpc.Core;
global using Polly;